name: Build .NET Framework 4.8 Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Framework 4.8 SDK
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install NuGet
      run: nuget restore Inventory.sln

    - name: Build project with MSBuild
      run: msbuild Inventory.sln /p:Configuration=Release
