# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
name: CI for .NET Framework 4.8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout code from repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    # Step 3: Setup NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.6

    # Step 4: Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore IMS_staging.sln

    # Step 5: Build the project
    - name: Build Solution
      run: msbuild IMS_staging.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.8
