name: CI for .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.6

    - name: Restore NuGet packages
      run: nuget restore ./IMS_staging.sln

    - name: Build Solution
      run: msbuild ./IMS_staging.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.8

    - name: List files in root directory (for debugging)
      run: dir ${{ github.workspace }}

    - name: List files in bin directory (for debugging)
      run: dir ${{ github.workspace }}/bin

    - name: Create Artifact ZIP
      run: Compress-Archive -Path ${{ github.workspace }}/bin/* -DestinationPath ./build-artifacts.zip

    - name: Verify Artifact ZIP (Checksum)
      run: |
        certutil -hashfile ./build-artifacts.zip SHA256

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build-artifacts.zip

    # Establish VPN Connection
    - name: Pritunl Client GitHub Action
      uses: nathanielvarona/pritunl-client-github-action@v1.6.8
      with:
        profile-file: ${{ secrets.PRITUNL_PROFILE }} # Provide the Pritunl profile (.ovpn or .wg) as a secret
        profile-pin: ${{ secrets.PRITUNL_PIN }}      # Provide the profile PIN/password as a secret
        vpn-mode: ovpn                              # Default mode is OpenVPN
        start-connection: true                      # Automatically start VPN connection
        ready-profile-timeout: 10                   # Adjust timeout as necessary
        established-connection-timeout: 60          # Adjust timeout for connection establishment

    # Deploy to IIS Server over VPN
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.IMSKEY }}

    - name: Deploy to IIS Server
      run: |
        # Ensure the destination folder on the server exists (optional)
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "mkdir -p C:/inetpub/wwwroot/IMS_staging"

        # Check that the file is transferred correctly (optional)
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "dir C:/inetpub/wwwroot/IMS_staging/"

        # Copy the build artifacts to the IIS server
        scp -r ./build-artifacts.zip ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/C:/inetpub/wwwroot/IMS_staging/

        # Unzip the build artifacts on the IIS server
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "powershell -Command Expand-Archive -Path 'C:/inetpub/wwwroot/IMS_staging/build-artifacts.zip' -DestinationPath 'C:/inetpub/wwwroot/IMS_staging/'"

        # Optionally, restart IIS application pool to refresh the deployment
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "iisreset"
