name: CI for .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.0.6

    - name: Restore NuGet packages
      run: nuget restore ./IMS_staging.sln

    - name: Build Solution
      run: msbuild ./IMS_staging.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.8

    - name: List files in root directory (for debugging)
      run: dir ${{ github.workspace }}

    - name: List files in IMS_staging directory (for debugging)
      run: dir ${{ github.workspace }}/IMS_staging

    - name: Create Artifact ZIP
      run: Compress-Archive -Path ${{ github.workspace }}/IMS_staging/bin/* -DestinationPath ./build-artifacts.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build-artifacts.zip
